# Generated by Django 3.1.6 on 2021-02-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_auto_20210210_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='transparent', max_length=20, verbose_name='タグの色'),
        ),
    ]
