# Generated by Django 3.1.6 on 2021-02-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='grey', max_length=20, verbose_name='タグの色'),
        ),
    ]
